### ISSUE TITLE
loading error when using std::string

### ISSUE THREAD

**Issue by KunaPrime** [goertzenator/nifpp#12]
when using nifpp like this

```cpp
std::string s {"something"};
nifpp::TERM a  = nifpp::make(env,s);
return a;
```

upon calling function i get:

```erl
{load_failed,"Failed to load NIF library: './priv/substitutor.so: undefined symbol: __gxx_personality_v0'"}
```

i'm on ubuntu 16.04, and i'm compiling with g++

**Comment by goertzenator** [comment]
Does [this] (http://stackoverflow.com/questions/203548/undefined-symbol-gxx-personality-v0-on-link) help?

**Comment by KunaPrime** [comment]
that is one of the very fist things that i tried so far and it doesn't work.
the thing is, i'm building my project as escript rebar3 template and it seems that even if i change compiler and c++11 flag it is not working. 
I have "transplanted" module and c++ implementiation in your example folder and used your make file 
building and running `ldd -r substitutor.so` gives me clean report but `enif_make_string_len` is still udefined. Reading other post situation with `enif_make_string_len` is expected and fine.

I have to take closer look on both makefiles to pin point what's wrong.

**Comment by KunaPrime** [comment]
I have found the problem. The thing is, i was compiling an linking i two different steps, and as i have reused makefile form another project compiling was done with `g++` and linking with `cc` this is obvious wrong thing. Once i have linked with `g++` everything worked fine. Thank you for quick response.
