### ISSUE TITLE
Resource that lasts until explicitly destroyed

### ISSUE THREAD

**Issue by fire** [goertzenator/nifpp#9]
Is it possible to have a construct_resource that lasts until manually destroyed?

**Comment by goertzenator** [comment]
Consider wrapping your resource type in [boost::optional](http://www.boost.org/doc/libs/1_59_0/libs/optional/doc/html/index.html) or std::unique_ptr.  With these you can manually destroy the contained object before Erlang gets around to garbage collecting the resource.
